import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#0a0a0f' },
  appBar: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 56 : 40,
    paddingBottom: 16,
    backgroundColor: '#0a0a0f',
  },
  webContainerAppBar: {
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  appBarLeft: { flexDirection: 'row', alignItems: 'center' },
  avatar: { width: 44, height: 44, borderRadius: 22, marginRight: 12 },
  locationText: { color: '#8b91a8', fontSize: 11, fontWeight: '700', letterSpacing: 0.5, marginBottom: 2 },
  appBarTitle: { color: '#d4a5ff', fontSize: 18, fontWeight: '800' },
  appBarTitleSecondary: { color: '#00d2ff' },
  bellIcon: { padding: 4 },
  scroll: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 100, alignItems: 'center' },
  webContainer: { width: '100%', maxWidth: 480 },
  greetingTitle: { color: '#ffffff', fontSize: 28, fontWeight: '800', marginBottom: 6 },
  greetingSub: { color: '#a0a8c0', fontSize: 14, marginBottom: 24 },
  bannerWrapper: { borderRadius: 28, overflow: 'hidden', marginBottom: 32 },
  banner: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 28, paddingVertical: 32 },
  bannerOverline: { color: '#13131c', fontSize: 11, fontWeight: '800', letterSpacing: 2, marginBottom: 8 },
  bannerTitle: { color: '#000000', fontSize: 32, fontWeight: '900', lineHeight: 36 },
  bannerIconCircle: { width: 64, height: 64, borderRadius: 32, backgroundColor: 'rgba(255,255,255,0.3)', alignItems: 'center', justifyContent: 'center' },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  sectionTitle: { color: '#ffffff', fontSize: 18, fontWeight: '700' },
  viewAll: { color: '#00d2ff', fontSize: 13, fontWeight: '700' },
  onlineBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#13131c', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  onlineDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#00e676', marginRight: 6 },
  onlineText: { color: '#8b91a8', fontSize: 11, fontWeight: '600' },
  categoriesGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  categoryCard: { width: '48%', backgroundColor: '#13131c', borderRadius: 24, padding: 20, marginBottom: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.03)' },
  catIconWrapper: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginBottom: 16 },
  catType: { color: '#8b91a8', fontSize: 10, fontWeight: '800', letterSpacing: 1.5, marginBottom: 4 },
  catLabel: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
  workerCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#13131c', borderRadius: 24, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.03)' },
  workerAvatarWrapper: { position: 'relative', marginRight: 16 },
  workerAvatar: { width: 60, height: 60, borderRadius: 30 },
  workerOnlineDot: { position: 'absolute', bottom: 2, right: 2, width: 12, height: 12, borderRadius: 6, backgroundColor: '#00e676', borderWidth: 2, borderColor: '#13131c' },
  workerInfo: { flex: 1 },
  workerNameRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  workerName: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  ratingBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(0, 230, 118, 0.1)', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 8 },
  ratingText: { color: '#ffffff', fontSize: 11, fontWeight: '700', marginLeft: 4 },
  workerRole: { color: '#8b91a8', fontSize: 13, fontWeight: '500' },
});
