import { StyleSheet, Dimensions } from 'react-native';
import { Colors, Spacing, BorderRadius, FontSize, GradientColors } from '../constants/theme';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: Colors.bg },
  scroll: { flexGrow: 1, paddingBottom: 32, alignItems: 'center' },
  webContainer: { width: '100%', maxWidth: 480 },
  topBar: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingTop: 52, paddingBottom: 8, zIndex: 99 },
  langSelector: { position: 'relative', zIndex: 100 },
  langButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.bgCard, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 22, borderWidth: 1, borderColor: Colors.border },
  langText: { color: Colors.textSecondary, fontSize: FontSize.xs, fontWeight: '700', letterSpacing: 0.8 },
  langDropdown: { position: 'absolute', top: 42, right: 0, backgroundColor: Colors.bgCard, borderRadius: BorderRadius.md, borderWidth: 1, borderColor: Colors.border, minWidth: 130, overflow: 'hidden', elevation: 10 },
  langOption: { paddingHorizontal: 16, paddingVertical: 12 },
  langOptionActive: { backgroundColor: 'rgba(91,200,245,0.08)' },
  langOptionText: { color: Colors.textSecondary, fontSize: FontSize.md, fontWeight: '500' },
  logoSection: { alignItems: 'center', marginTop: 12, marginBottom: 6 },
  logoOuter: { position: 'relative' },
  logoGradient: { width: 76, height: 76, borderRadius: 38, alignItems: 'center', justifyContent: 'center', shadowColor: Colors.accent, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.5, shadowRadius: 16, elevation: 14 },
  liveBadge: { position: 'absolute', bottom: -4, backgroundColor: Colors.success, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, left: '50%', transform: [{ translateX: -20 }] },
  liveText: { color: '#fff', fontSize: 9, fontWeight: '800', letterSpacing: 1 },
  titleSection: { alignItems: 'center', marginTop: 18, marginBottom: 20, paddingHorizontal: 20 },
  brandName: { fontSize: FontSize.display, fontWeight: '900', color: Colors.accent, letterSpacing: 0.5 },
  welcomeEn: { fontSize: FontSize.xl, fontWeight: '700', color: Colors.textPrimary, marginTop: 4 },
  welcomeMr: { fontSize: FontSize.base, color: Colors.textSecondary, marginTop: 4 },
  heroCard: { marginHorizontal: 16, borderRadius: BorderRadius.xl, overflow: 'hidden', height: 200, marginBottom: 24, backgroundColor: Colors.bgCard },
  heroImage: { width: '100%', height: '100%', position: 'absolute' },
  heroOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 120 },
  heroBadgeText: { position: 'absolute', top: 14, left: 16, color: Colors.accent, fontSize: FontSize.xs, fontWeight: '800', letterSpacing: 1.5 },
  heroCaption: { position: 'absolute', bottom: 16, left: 16, right: 16, color: '#d0d8f0', fontSize: FontSize.sm, lineHeight: 20, fontWeight: '500' },
  inputCard: { marginHorizontal: 16, backgroundColor: Colors.bgCard, borderRadius: BorderRadius.xl, padding: 22, borderWidth: 1, borderColor: Colors.borderLight, marginBottom: 28 },
  inputLabel: { color: Colors.textDisabled, fontSize: FontSize.xs, fontWeight: '700', letterSpacing: 1.2, marginBottom: 12 },
  phoneRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.bgInput, borderRadius: BorderRadius.md, height: 56, marginBottom: 16, borderWidth: 1.5, borderColor: Colors.border, overflow: 'hidden' },
  countryCode: { paddingHorizontal: 16, height: '100%', justifyContent: 'center' },
  countryCodeText: { color: Colors.textPrimary, fontSize: FontSize.lg, fontWeight: '700' },
  dividerV: { width: 1, height: '60%', backgroundColor: Colors.bgMuted },
  otpHint: { color: Colors.textDisabled, fontSize: FontSize.sm, textAlign: 'center', marginTop: 14 },
  trustSection: { paddingHorizontal: 24, marginBottom: 24 },
  trustDivider: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  trustLine: { flex: 1, height: 1, backgroundColor: Colors.borderLight },
  trustLabel: { color: Colors.textDisabled, fontSize: FontSize.xs, fontWeight: '700', letterSpacing: 1.5, paddingHorizontal: 12 },
  trustRow: { flexDirection: 'row', justifyContent: 'space-around' },
  trustItem: { alignItems: 'center', gap: 8 },
  trustIcon: { width: 52, height: 52, borderRadius: 26, backgroundColor: Colors.bgCard, borderWidth: 1, borderColor: Colors.borderLight, alignItems: 'center', justifyContent: 'center' },
  trustText: { color: Colors.textDisabled, fontSize: FontSize.xs, fontWeight: '700', letterSpacing: 1.2, marginTop: 4 },
  footer: { paddingHorizontal: 28, alignItems: 'center' },
  footerText: { color: Colors.textDisabled, fontSize: FontSize.sm, textAlign: 'center', lineHeight: 18 },
  footerLink: { color: Colors.accent, fontWeight: '600' },
});
