import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#0a0a0f' },
  appBar: { paddingHorizontal: 20, paddingTop: Platform.OS === 'ios' ? 56 : 40, paddingBottom: 16, backgroundColor: '#0a0a0f' },
  webContainerAppBar: { width: '100%', maxWidth: 480, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  appBarLeft: { flexDirection: 'row', alignItems: 'center' },
  avatar: { width: 36, height: 36, borderRadius: 18, marginRight: 12 },
  appBarTitle: { color: '#ffffff', fontSize: 18, fontWeight: '800' },
  appBarTitleSecondary: { color: '#00d2ff' },
  bellIcon: { padding: 4 },
  scroll: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 80, alignItems: 'center' },
  webContainer: { width: '100%', maxWidth: 480 },
  pageTitle: { color: '#ffffff', fontSize: 32, fontWeight: '800', marginBottom: 6 },
  pageSubtitle: { color: '#8b91a8', fontSize: 14, marginBottom: 32, lineHeight: 22 },
  inputGroup: { marginBottom: 24 },
  inputLabel: { color: '#b070ff', fontSize: 11, fontWeight: '800', letterSpacing: 1.5, marginBottom: 12 },
  textAreaWrapper: { backgroundColor: '#13131c', borderRadius: 24, padding: 16, height: 120, borderWidth: 1, borderColor: 'rgba(255,255,255,0.03)' },
  textArea: { color: '#ffffff', fontSize: 15, flex: 1 },
  inputBox: { backgroundColor: '#13131c', borderRadius: 20, paddingHorizontal: 16, height: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, borderColor: 'rgba(255,255,255,0.03)' },
  inputText: { color: '#ffffff', fontSize: 15, fontWeight: '500' },
  currencySymbol: { color: '#00d2ff', fontSize: 18, fontWeight: '800', marginRight: 12 },
  inputField: { color: '#ffffff', fontSize: 16, fontWeight: '700', flex: 1 },
  photoUploadBox: { height: 110, borderRadius: 24, borderWidth: 1.5, borderColor: 'rgba(255,255,255,0.1)', borderStyle: 'dashed', alignItems: 'center', justifyContent: 'center', backgroundColor: '#0a0a0f' },
  photoUploadText: { color: '#a0a8c0', fontSize: 12, marginTop: 10, fontWeight: '500' },
  mapContainer: { height: 130, borderRadius: 24, overflow: 'hidden', position: 'relative', borderWidth: 1, borderColor: 'rgba(255,255,255,0.03)' },
  mapBackground: { flex: 1 },
  mapOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', backgroundColor: 'rgba(10,10,15,0.4)' },
  locationPinRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#0a0a0f', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 16 },
  locationText: { color: '#ffffff', fontSize: 12, fontWeight: '700', marginLeft: 6 },
  targetIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#1a1f33', alignItems: 'center', justifyContent: 'center' },
  urgentCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#13131c', borderRadius: 24, padding: 20, marginBottom: 32, borderWidth: 1, borderColor: 'rgba(255,255,255,0.03)' },
  urgentIconWrapper: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255, 82, 82, 0.1)', alignItems: 'center', justifyContent: 'center', marginRight: 16 },
  urgentTextCol: { flex: 1, paddingRight: 10 },
  urgentTitle: { color: '#ffffff', fontSize: 15, fontWeight: '700', marginBottom: 4 },
  urgentSub: { color: '#8b91a8', fontSize: 11, lineHeight: 16 },
  postButton: { width: '100%', marginBottom: 20 },
  postBtnGradient: { height: 60, borderRadius: 30, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  postBtnText: { color: '#0d0d14', fontSize: 18, fontWeight: '900', letterSpacing: 0.5 },
});
